# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd1e73c6f32e495689a4c7531292746a49b2456c48fa523a7d58a85a2cf8b086c5d0fc40a3c67c8b55b57325d464a7105c096f6f9fe78ef95284367839ce8895

test:
  secret_key_base: c58bb6869c36b8b4a243122cc7caf52fffecc1dade6687c0bc12755fb02295beede1ae9b9c889c0431ef03193f7251d929afb1b78d6f02347d09c3baed60b99f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
